### ISSUE TITLE
Don't let people sign up with different accounts that use the same email

### ISSUE THREAD

**Issue by wdoug** [codefordenver/members#107]

**Comment by sungbae** [comment]
Per documentations from auth0 this is the intended functionality. They have support to link these accounts metadata. I don't like this approach since it's not ideal to have multiple users with the same email in the first place... Plus it's not free. Maybe have to look into avoiding mutation when we already have the same email in the database.

https://auth0.com/docs/link-accounts

**Comment by sungbae** [comment]
#121 is created as continuation of this feature.
