### ISSUE TITLE
Don't require page reload on signup/login

### ISSUE THREAD

**Issue by wdoug** [codefordenver/members#127]
Right now when a user signs up or logs in the page does a full refresh to show them as logged in. This seems to sometimes create issues, and is very slow.

**Comment by mugwump303** [comment]
I think the cause is the "window.location.reload()" call in the LoginAuth0 component. 
We probably need to pass the new user data into one of the parent components, then the Login button should be re-rendered with the correct user data without a full page reload.

I think we can use "refetch", "update", or "refetchQueries"

**Comment by mugwump303** [comment]
I'm not sure if the way I ended up doing it is good. 

Here are some links to Apollo docs that looked promising. I couldn't get them to work though.

https://www.apollographql.com/docs/react/basics/setup.html#compose
https://www.apollographql.com/docs/react/basics/mutations.html#graphql-mutation-options-update
https://www.apollographql.com/docs/react/basics/mutations.html#graphql-mutation-options-refetchQueries
