### ISSUE TITLE
Make sure we're no longer using Auth0 lock [It goes away on July 16th]

### ISSUE THREAD

**Issue by wdoug** [codefordenver/members#230]
![Screen Shot 2018-06-11 at 5.45.17 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53d30e7b82b317f7d9ad0fbb/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256455f26b7191a37df1162e4f5e585ecc3c4a4356bcbbd671f3e57862804e0ee4d66b0e27976f17afbf8518b701ba21d94ed4e4ed8a4dd2f42f67b6d5db1063474f4dcbed5727a19e41c95df443e64b55ad163164e2772431.png)

**Comment by dchao19** [comment]
I can confirm this project isn't using Auth0 Lock. That was a legacy widget that acted as its own login widget (i.e username and password fields). The current authentication flow works by using the Auth0 JS sdk to redirect to our auth0 tenancy and generate an access token entirely separate from the application itself. 

The error message occurs because your Auth0 account still has the lock api enabled.
