### ISSUE TITLE
Set up travis.ci for eslint and tests

### ISSUE THREAD

**Issue by wdoug** [codefordenver/members#57]
As a developer, I want to make sure our linting and tests are catching errors for me, so that I don't have to.

**Comment by nlkluth** [comment]
TODO:
- install eslint `npm install --save-dev eslint`
- get eslint hooked up through sublime-linter
- can you run eslint? `./node_modules/.bin/eslint <filepath> `: filepath might be ./src
- map eslint to npm script so that i can do `npm run eslint`- something like "eslint": "eslint <filepath>" https://gist.github.com/ronapelbaum/ef3c3459f01b002d0d719ca205401174
- add .travis.yml
- add travis commands - check https://travis-ci.org/codefordenver/members
