### ISSUE TITLE
Figure out how to upgrade to the new framework of Graphcool

### ISSUE THREAD

**Issue by wdoug** [codefordenver/members#59]
This should greatly improve our collaboration abilities on this project.
https://blog.graph.cool/graphcool-framework-preview-ff42081b1333

**Comment by wdoug** [comment]
We won't be able to use any of the direct plugins with this new version anymore, which means we will need code for managing our integration with Auth0. This template might do the trick for us though: https://github.com/graphcool/templates/tree/master/community/auth/auth0-database-authentication

**Comment by wdoug** [comment]
Waiting on https://github.com/graphcool/templates/pull/112

**Comment by timwis** [comment]
FYI, that template works today -- it's just a few improvements being made to it. Since `graphcool add-template` literally just copies the code into a file in your local project, you could do it right now unless you're waiting for the graphcool team's official blessing of the template.

Hello from Philly, btw. This project sounds cool! Philly uses [laddr](https://github.com/CodeForPhilly/laddr).
